### ISSUE TITLE
Trip route

### ISSUE THREAD

**Issue by VilmerJ** [ollisco/dynweb-project#11]
Allow the user to see the route of the trip. Could be displayed with the information component or separate.

**Comment by oscarcusin** [comment]
Also don't show anything in information view until a search has been performed.

**Comment by VilmerJ** [comment]
Could take a lot of inspiration from Google or Apple Maps.

**Comment by henryl0u** [comment]
Tror det är bättre om någon som har koll på SLs api grejer osv tar denna
